language: python

# We support from Python 2.4 to 2.7
python:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"

# we need cmake
install:
  - sudo apt-get install cmake

# test script
script:
  - cmake .
  - ctest -V .

# Notify the mailing list
notifications:
 recipients:
   - editorconfig@googlegroups.com
 email:
   on_success: change
   on_failure: always
